### ISSUE TITLE
Remove the Wrapper Zip for releases

### ISSUE THREAD

**Issue by canausa** [hashicorp/serf#275]
Serf is a single binary for linux as such it is irritating to download a file call "0.6.4_linux_amd64.zip" to then install unzip to get a single file called serf.

if you are experimenting serf and consul you get one binary called 0.6.4_linux_amd.zip and one called 0.5.0_linux_amd64.zip and trying to remember which one is serf to extract with unzip you just installed.

**Comment by ryanuber** [comment]
@canausa we use Zip mainly because it is the most universally supported archive/compression format across the various OS'es we support. We actually get a significant size saving by distributing in a compressed format. In this case, serf is ~13MB uncompressed, and ~3MB compressed. For now we plan to stick with .zip, but thanks for the suggestion!

**Comment by canausa** [comment]
If your argument is that a download 13MB file is faster to download then a ~3MB zip format then I will have to disagree.

I setup a simple test using apache and mod_deflate using compression level 9 I could compress the over the wire transfer of the binary serf to 3,272,624 bytes. The zipped serf binary could only be compressed to 3,285,868 ( 0.4 % savings ). If less bytes over the wire is the end goal then an unzip binary is better. But lets also look at the user experience.

For zipped files
  Windows:
    Download file
    unzip file ( as windows has software built in)
    run command
  OSX:
   download file
   unzip file ( OSX already decompresses it for you if you use a browser  but not the CLI) 
   run command 
  Linux:
    download file
    install unzip software
    unzip file
    run command

For unzipped Binary:
  Windows:
    download file
    run command
  OSX:
   download file
   run command
  Linux:
    download file
    make executable
    run command

For an overall user experience you can reduce friction to the user by removing ( on average ) 1 step from each Platform.

If your argument for better distribution is based more on disk space for the user. Your current solution uses 23% more disk space when trying to install the software.

If your argument for better distribution is based on transferring the file from one machine to another then you can use the same reason you told me in the ticket about Debian packages. Compress it your self.

**Comment by mitchellh** [comment]
@canausa I apologize if we misconveyed information here. Our argument is none of the above of what you brought up. I'm sure we've explained it elsewhere before (certainly at least on other projects) but I'll make sure to repeat here for Google or what-have-you.

Before I start, I want to absolutely agree with you that for a better UX, platform-native packaging would be better. No disagreement there.

We choose zip as a practicality for us. We maintain a large number of projects, and we don't want to adopt a platform-specific packaging format without being able to roll that out to all our projects. Vagrant is an exception since its whole build process is quite a bit different. It is very easy for us in our build scripts to cross compile locally and then just zip everything.

For a marginally better user experience, using platform-native packaging would indeed be better, I don't disagree. But no sane individual will ever say "This tool really solves every problem I have, but I can't use it because I need to write a one-line bash script or repackage it with `fpm`". Will it push some people away from initially trying it? Perhaps, but given the incredible adoption of most of our tools that use ZIP as the format, I'm going to guess that its not a big deal.

We're not saying "NO!" to platform-native packaging, we're just saying "not yet" and with a low priority. We'd much rather focus on shipping stability improvements, great new features, improving documentation, and in generally solving critical problems before we make marginal improvements to an already quite-simple (`unzip`) install process. 

So, I'm sorry if this isn't what you want to hear, but we do our best to make technically excellent software with a great UX (perhaps not perfect, but great) and make it free, and I believe we achieve that. Over time, we'll improve even more, but it takes time, and it also takes help from the community to achieve all our goals. 

Given that, if you want to build a set of scripts to cross-compile our Go binaries, turn them into platform-native packages, and setup the proper HTTP endpoints (Terraform would be a good tool for this), then you'd be a hero and we certainly wouldn't turn it away. 

But if not, you'll have to struggle a bit longer with writing that one-liner install script, and I'm sorry.
