### ISSUE TITLE
Bad overflow handling in GetBindAddr

### ISSUE THREAD

**Issue by josharian** [hashicorp/serf#295]
at https://github.com/hashicorp/serf/blob/master/testutil/addr.go#L18

```go
var bindNum byte

// ...

	bindNum++
	if bindNum > 255 {
		bindNum = 10
	}
```

That should probably be `bindNum == 0`. Caught by a [proposed vet check](https://go-review.googlesource.com/#/c/11252/).

Easy fix for a new contributor? :)

**Comment by slackpad** [comment]
@josharian indeed that's a little shady! We'd be happy to merge a PR that fixes it :-)

**Comment by ryanuber** [comment]
So I think this is actually intentional. Since the unit tests keep binding to the next address, once we reach 256 we need to start over again. It's not the absolute best because we could in theory try binding the same IP twice, but so far it hasn't been problematic because we don't have 250+ unit tests running concurrently, so they just get recycled. I think cycling through 10-255 is probably OK for now. A better fix might be to increment the ports we bind to and just stick with 127.0.0.1 for the bind address.

**Comment by ryanuber** [comment]
@slackpad clued me in to the `byte` thing - Should have read the link. Makes sense!
