### ISSUE TITLE
How to search for members by tags?

### ISSUE THREAD

**Issue by ssenaria** [hashicorp/serf#371]
I've tried the following and i can't get the two members to return.

    serf members -tag host_type=web -tag host_type=batch
    serf members -tag host_type=web host_type=batch

The members

    node1.localdomain  10.199.1.99:7946  alive environment_id=sf_phl,host_type=batch,cluster_group=odd,datacenter=phl
    node2.localdomain   10.199.1.50:7946  alive environment_id=sf_phl,host_type=web,cluster_group=odd,datacenter=phl
    node3.localdomain   10.199.1.50:7946  alive environment_id=sf_phl,host_type=perl,cluster_group=odd,datacenter=phl

**Comment by ben-bensdevzone** [comment]
Hi ssenaria,

I just tested your query with Serf 0.6.4. It looks like the issue here is that you cannot combine two tag queries the way you've tried. It actually works fine if you're querying two different tags ("host_type" and "cluster_id", for example). You're trying to select a subgroup of nodes based on a single tag value though. What you can do in this case is using a regex. Basically, to retrieve a subset of nodes that are either of type "batch" or of type "web", you could write the query like this:

`serf members -tag type="batch|web"`

The above regex will match any member that is either web or batch. I hope this helps. 

Cheeers,
Ben

**Comment by ssenaria** [comment]
I forgot about this issue and neglected to update it. I tried what you wrote but I don't recall it working. What did work was the following command.

    serf members -tag type=".*batch|web.*"
