### ISSUE TITLE
how to use serf as library

### ISSUE THREAD

**Issue by fithisux** [hashicorp/serf#377]
My use case is a Golang cli progam that joins a cluster and intercepts node failure events. Any pointers or examples?

**Comment by slackpad** [comment]
Hi @fithisux Consul does this and is worth a look as an example. Here are the main integration points:

* https://github.com/hashicorp/consul/blob/master/consul/serf.go
* https://github.com/hashicorp/consul/blob/master/consul/client.go
* https://github.com/hashicorp/consul/blob/master/consul/server.go

Also, not sure if you saw event handlers but they are an easy way to get these cluster events and run scripts using just Serf:

https://www.serfdom.io/docs/agent/event-handlers.html

Similarly, if you are running Serf agents already, you can use the stream API to get these events by talking to the agent instead of joining the cluster:

https://www.serfdom.io/docs/agent/rpc.html

There's a Go client library for this API:

https://github.com/hashicorp/serf/tree/master/client

Hope that helps!
